### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by ibc** [heavyset/redux-webextension#3]
Hi, thanks for this project. It seems very useful.

Just wondering if this is maintained as there are no much commits and the latest was done 2 months ago.

Thanks a lot.

**Comment by gabrielg** [comment]
Hi there,

It is indeed maintained, there just hasn't been a need to work on it lately. Thank you for the kind comments!

**Comment by ibc** [comment]
Thanks. I'm testing it right now. It works nice for now :)
